### ISSUE TITLE
Error in adding two numbers in javascript

### ISSUE THREAD

**Issue by mjtechworks** [mjtechworks/ChatGPT-DiscordBot#1]
0.0001 + 0.0001 + 0.0001 = 0.00030000000000000003
what's up with javascript?

**Comment by frozenflux2** [comment]
The result you mentioned is not specific to JavaScript, but rather a common issue in floating-point arithmetic. It occurs due to the way numbers with fractional parts are stored and represented in computer systems.

Most programming languages, including JavaScript, use floating-point representation to handle decimal numbers. However, floating-point arithmetic may encounter precision errors when dealing with certain decimal values.

In your example, 0.0001 is a recurring decimal in binary representation. When you add multiple such numbers together, the precision error accumulates, resulting in a slight deviation from the expected result.

To mitigate this issue, programmers often resort to techniques like rounding the result to a desired number of decimal places or using specialized libraries that handle decimal arithmetic with greater precision. In JavaScript, you can use methods like toFixed() or libraries like BigDecimal.js to achieve more accurate computations with decimal numbers.
